language: python

services:
  - docker

before_install:
- docker pull jkern337/py2:latest
- ls -la


jobs:
  include:
    - stage: unit_test
      script: docker run -v `pwd`:/data -w /data/tests jkern337/py2:latest /bin/bash -c "source /root/.bashrc && pytest"