language: python

services:
  - docker

before_install:
- docker pull jkern337/py2:latest
- docker ps -a

script: 
- docker run -v `pwd`/AUT:/data -w /data/tests jkern337/py2:latest /bin/bash -c "source /root/.bashrc && pytest"