language: python

env:
  global:
    - secure: "T9wOaUOi59igKAo0noVyXXG1QGDMjG206AG+oS+SuPeA91HSDAVYp8f5jTRO9PcAUNrjIc/0jcOac8AVE3dmLe6Y587izVGmlc0u3K+471GAxdRX2t+growab8XIRinOBrnA0PrJHFf6MrPGIu8M607OsZwNi4j8Ey9idCegRh/NP5zGM50SqEiRlBP21JsuT1uQvoLo1IOSIcOBdceT23lXsJO+PN1GhF8xWBDNGjO1xFqIYekeDQs0bT/ThpAXZLdgqF9QZJHOOFiQdVEJNzgbL/+yQzJbbf4fns4rbimINe4GqtbeH92A+MYn/Mx6XrNJ1NCNxnCx7ezjorFVJWw0XavMcgIqj3L2DeZkVN5yRKXLTjFB+K0k+0peeZN+eFPutbW4uF0zw9ThciXF+2FR0TgrdsZZlCqH4cceWTLnYmTrIy0Umfmg5an2HCVlrcSiHX+v5IqsWCfhwZP06t1ZybxSZ7D4IJwSp/10QzEWTwBs0OdM6hF2fp+/V2wApb1NAM/rm+TGsNpAiNWaP6md8Wz/eEwus/f1GuO9WhnboHE7xa44gwDod4ElChcppT2IEcTRiliqVJa38wfnQuXAoMRw2/jHCeefEB0XpysfSwqifpqCG9GKWqBCxbwnaFHFdXqQlEy3MT0R8Mv9cXro9cJHn+vFjxifEssjKY4="
    - secure: "DwbzZ+yvpQMTZi8E/iFVtdNxWSzq4/2ygQWbmWiKKXOhsLc+waqW5T6ySmn8geGZNEKJDEPn2I2/v07apQqy3yPWUiXNipHb3lVjaRcVGgfQ6POhBuU+GNsvjJWbXoO5ZPCBhQhZZe4RTItYnXOTPLCOdyp4QtDmDMqVgH3zqEf0IOVwWPYMjNcuFWwUSY4MrPfyxwon00vW6/HoM4wIAZwomZIRo6O3Y96dIFtQsve8Ng25zxcWq+r6PrfvP7RmrNKwPzNzCmlu0N7InRJr2AxNBlcmFz2HRUH8CJ4zdMK664GoVS1pL+bQ1eIwcrmkc0WDrHo1URu1CWfT6OL44VGuPu+1tmuR4VVpD/xN5nr3n8D7jL/pN7f2x/5RWyTWquQzWotivMPa8D0J83jTDy6tz/XnDKzRCIQxGDziIucHIcsDkGgy8EIfTIxL1SwhP9mhWBbY5DXWNpixt59n8dhjnegz7QtX01vV49n9nZRUzMEzztnAHP7oYPx+K5cla86WY494Ppkuspv4Rma8lmJDwblr4zQLTdOxIhW5lSLHF6jK1SlFhrl1VtXXDRJ4+pfXDyLJvTyYKKNIeLQey5pfhMMKljIjZDUkclLffdv/a5tMto+dFg2DhpaHUykyV7rfTg4I8kc8lrc5SkzIRMH+28PEnj2+NemKlnlb0GA="


services:
  - docker

before_install:
- docker login -p $DOCKER_PASSWORD -u $DOCKER_USER
- docker pull jkern337/py2:latest
- ls -la


jobs:
  include:
    - stage: unit_test
      if: branch = master
      script: docker run -v `pwd`:/data -w /data/tests jkern337/py2:latest /bin/bash -c "source /root/.bashrc && pytest"